image: gradle:jdk19

stages:
  - build
  - test
  - visualize
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

build:
  stage: build
  script: gradle --parallel --build-cache assemble --info

  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull-push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle check
  needs:
    - build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    reports:
      junit:
        - build/test-results/test/*.xml
    paths:
      - build/jacoco/jacoco.xml
    when: always
  coverage: '/    - Instruction Coverage: ([0-9.]+)%/'

coverage-visualization:
  stage: visualize
  image: jhbuchanan21/jacoco2cobertura:latest
  script:
    - python /opt/cover2cover.py build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > build/cobertura.xml
  needs:
    - test
  when: always
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/cobertura.xml